name: deploy on llamaEdge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: build
        run: |
          npm install
          npm run build

      - name: Clone target repository
        run: git clone https://github.com/LlamaEdge/www.git

      - name: Copy build files
        run: |
          cd www
          mkdir -p docs
          cp -r ../build/* ./docs

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd www
          git remote set-url --push origin https://JYC0413:$GITHUB_TOKEN@github.com/LlamaEdge/www.git
          git config --local user.email "juyichen0413@foxmail.com"
          git config --local user.name "JYC0413"
          git add .
          git commit -m "Build and deploy docs"
          git push
